### ISSUE TITLE
Ability to print a spell sheet (in multiple pages)

### ISSUE THREAD

**Issue by spetzel2020** [spetzel2020/spell-better#5]

**Comment by akrigline** [comment]
```css
/* Makes PopOuted OGL Character Sheet Spellbook tab print with multiple pages. */
@media print {
    .app {
         max-height: unset !important;
    }
    .window-content {
        display: block;
    }
    .window-content > form {
        display: block;
    }
    section, form, div:not(.item-image){
        overflow: auto !important;
        height: auto !important;
    }
}

```

Here's a Print Media Query stylesheet which will override the OGL Sheet in a PopOut window such that it will print spanning multiple pages.
